image: maven:3.9.10-amazoncorretto-21-al2023

.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - init
  - test
  - build

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=.m2/repository"

init:
  stage: init
  rules:
    - !reference [ .default_rules, rules ]
  script:
    - echo "Setting up Java and resolving dependencies"
    - mvn $MAVEN_CLI_OPTS dependency:resolve
  cache:
    paths:
      - .m2/repository

test:
  stage: test
  rules:
    - !reference [ .default_rules, rules ]
  script:
    - mvn $MAVEN_CLI_OPTS test
  cache:
    paths:
      - .m2/repository
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    when: always
    expire_in: 1 week

build:
  stage: build
  rules:
    - !reference [ .default_rules, rules ]
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week