services:
  pg_auth-boost:
    image: postgres:latest
    container_name: pg_auth-boost
    environment:
      POSTGRES_USER: ${DEV_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE_NAME}
      PORT: ${DEV_DATABASE_PORT:-5436}
    ports:
      - "${DEV_DATABASE_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mail_auth-boost:
    image: axllent/mailpit
    container_name: mail_auth-boost
    ports:
      - "1026:1025" # SMTP
      - "8026:8025" # Web UI for interactions
    restart: unless-stopped

  app:
    build: .
    container_name: auth-boost-backend-prod
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DEV_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DEV_DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEV_DATABASE_PASSWORD}
      SPRING_MAIL_HOST: mail_auth-boost
      SPRING_MAIL_PORT: 1025
    depends_on:
      - pg_auth-boost
      - mail_auth-boost
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local