spring:
  datasource:
    url: ${TEST_DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: never
    include-message: never
    include-path: never
    include-stacktrace: never

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
